name: fedxgboost_mpi
dependencies:
- python=3.8
- numpy #=1.22.3
- cycler=0.11.0
- fonttools #=4.33.3
- kiwisolver=1.4.2
- matplotlib=3.5.1
- mpi4py #=3.1.3
- packaging=21.3
- pandas=1.4.2
- Pillow #=9.1.0
- pyparsing #=3.0.8
- python-dateutil=2.8.2
#- python-dp #=1.1.1
- pytz=2022.1
- scipy= #1.8.0
- six=1.16.0

# conda install -c conda-forge mpi4py
# pip install python-dp pyfhel scikit-learn phe

# conda install -c conda-forge openmpi mpi4py

# apt install openmpi-bin
